# Generated by Django 4.2.7 on 2024-11-10 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_room_room_type_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
