# Generated by Django 4.2.7 on 2024-11-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_room_alter_department_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examDate', models.DateField()),
                ('examTime', models.TimeField()),
                ('duration', models.PositiveBigIntegerField(help_text='Duration of the exam in minutes')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
        ),
    ]
