# Generated by Django 4.2.7 on 2024-11-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_roomid_schedule_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='sectionID',
            new_name='section',
        ),
    ]
